server:
  port: 9000
  servlet:
    context-path: /e-built-cloud

spring:
  data:
    redis:
      host: 43.138.10.223
      password: Ypd050243.
      database: 0
      port: 6379
      connect-timeout: 3000


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.ebuilt.ebuiltcloudlogin,controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn